// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAtUZNgoeOTFsRuDtjim9zTBPh7IPZWygk',
    appId: '1:169214446516:web:b5515483d442efe31180e1',
    messagingSenderId: '169214446516',
    projectId: 'test-1ef17',
    authDomain: 'test-1ef17.firebaseapp.com',
    databaseURL: 'https://test-1ef17-default-rtdb.firebaseio.com',
    storageBucket: 'test-1ef17.firebasestorage.app',
    measurementId: 'G-QRS41P3MWR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCLhIEIYEf5cMuJl8hYxoSWR0MbTSL7G4',
    appId: '1:169214446516:android:a20525e011864f581180e1',
    messagingSenderId: '169214446516',
    projectId: 'test-1ef17',
    databaseURL: 'https://test-1ef17-default-rtdb.firebaseio.com',
    storageBucket: 'test-1ef17.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBL99GIQwgziDFKrEAU_1HJsDPjUIOIMYc',
    appId: '1:169214446516:ios:2554e4e73af0fc351180e1',
    messagingSenderId: '169214446516',
    projectId: 'test-1ef17',
    databaseURL: 'https://test-1ef17-default-rtdb.firebaseio.com',
    storageBucket: 'test-1ef17.firebasestorage.app',
    iosBundleId: 'com.cybash.projects.gpsTrackingSystem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBL99GIQwgziDFKrEAU_1HJsDPjUIOIMYc',
    appId: '1:169214446516:ios:2554e4e73af0fc351180e1',
    messagingSenderId: '169214446516',
    projectId: 'test-1ef17',
    databaseURL: 'https://test-1ef17-default-rtdb.firebaseio.com',
    storageBucket: 'test-1ef17.firebasestorage.app',
    iosBundleId: 'com.cybash.projects.gpsTrackingSystem',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAtUZNgoeOTFsRuDtjim9zTBPh7IPZWygk',
    appId: '1:169214446516:web:e8efff5e3b73bc4a1180e1',
    messagingSenderId: '169214446516',
    projectId: 'test-1ef17',
    authDomain: 'test-1ef17.firebaseapp.com',
    databaseURL: 'https://test-1ef17-default-rtdb.firebaseio.com',
    storageBucket: 'test-1ef17.firebasestorage.app',
    measurementId: 'G-DXEW083QNM',
  );
}
